# Generated by Django 3.2.5 on 2021-07-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('key', models.CharField(max_length=15, unique=True)),
                ('hardware_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('last_activity', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
