# Generated by Django 3.2.5 on 2021-07-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensekeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='hardware_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='last_activity',
            field=models.DateTimeField(blank=True),
        ),
    ]
