# Generated by Django 3.2.5 on 2021-08-04 04:43

from django.db import migrations, models
import licensekeys.models


class Migration(migrations.Migration):

    dependencies = [
        ('licensekeys', '0002_auto_20210727_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.CharField(default=licensekeys.models.generate_license, editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
