# Generated by Django 3.2.5 on 2021-08-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensekeys', '0003_auto_20210804_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
